# Generated by Django 2.2.11 on 2020-03-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCleanedCrashData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.BigIntegerField(verbose_name='cid')),
                ('city', models.TextField(verbose_name='city')),
                ('latitude', models.FloatField(blank=True, max_length=8, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, max_length=8, null=True, verbose_name='longitude')),
                ('street_name', models.TextField(blank=True, null=True, verbose_name='streetName')),
                ('injured_count', models.TextField(blank=True, null=True, verbose_name='injuredCount')),
                ('crash_time', models.DateTimeField(blank=True, null=True, verbose_name='crashTime')),
            ],
        ),
    ]
