# Generated by Django 2.2.11 on 2020-03-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcleanedcrashdata',
            name='crash_date',
            field=models.DateField(blank=True, null=True, verbose_name='crashDate'),
        ),
    ]
